// Generated by generate_loq31.py — do not edit by hand.
const LOQ_CONFIG = {
 "version": "3.1",
 "generated": "2026-07-16",
 "scale": {
  "min": 1,
  "max": 6
 },
 "scoring": {
  "reverse_formula": "(max+1) - x",
  "domain_formula": "round(mean(keyed items) / max * 10, 1)"
 },
 "wheel_base_url": "https://lalayantsv.github.io/loq-wheel/loq31_wheel.html",
 "sections_tag": "SCR_SECTIONS",
 "clusters": [
  {
   "name": "Foundation",
   "color": "#324D47"
  },
  {
   "name": "Connection",
   "color": "#B8755E"
  },
  {
   "name": "Internal Flow",
   "color": "#6B8E5F"
  },
  {
   "name": "Expansion",
   "color": "#C19A47"
  }
 ],
 "domains": [
  {
   "code": "PWB",
   "name": "Physical Well-Being",
   "label": "Physical\nWell-Being",
   "cluster": "Foundation",
   "color": "#324D47",
   "gate": null
  },
  {
   "code": "FWB",
   "name": "Financial Well-Being",
   "label": "Financial\nWell-Being",
   "cluster": "Foundation",
   "color": "#42625B",
   "gate": null
  },
  {
   "code": "SEC",
   "name": "Safety & Security",
   "label": "Safety &\nSecurity",
   "cluster": "Foundation",
   "color": "#52776F",
   "gate": null
  },
  {
   "code": "LEN",
   "name": "Living Environment",
   "label": "Living\nEnvironment",
   "cluster": "Foundation",
   "color": "#628C83",
   "gate": null
  },
  {
   "code": "REL",
   "name": "Relations",
   "label": "Relations",
   "cluster": "Connection",
   "color": "#B8755E",
   "gate": null
  },
  {
   "code": "FAM",
   "name": "Family",
   "label": "Family",
   "cluster": "Connection",
   "color": "#BF7E66",
   "gate": null
  },
  {
   "code": "CID",
   "name": "Cultural Identity",
   "label": "Cultural\nIdentity",
   "cluster": "Connection",
   "color": "#C68870",
   "gate": null
  },
  {
   "code": "COM",
   "name": "Community Contribution",
   "label": "Community\nContribution",
   "cluster": "Connection",
   "color": "#D49B82",
   "gate": null
  },
  {
   "code": "PAR",
   "name": "Parenting & Caregiving",
   "label": "Parenting &\nCaregiving",
   "cluster": "Connection",
   "color": "#E2AE94",
   "gate": "1"
  },
  {
   "code": "SXI",
   "name": "Sexuality & Intimacy",
   "label": "Sexuality &\nIntimacy",
   "cluster": "Connection",
   "color": "#F0C1A6",
   "gate": "2"
  },
  {
   "code": "MWB",
   "name": "Mental Well-Being",
   "label": "Mental\nWell-Being",
   "cluster": "Internal Flow",
   "color": "#6B8E5F",
   "gate": null
  },
  {
   "code": "TMG",
   "name": "Time Management",
   "label": "Time\nManagement",
   "cluster": "Internal Flow",
   "color": "#7FA073",
   "gate": null
  },
  {
   "code": "REC",
   "name": "Recreation & Leisure",
   "label": "Recreation &\nLeisure",
   "cluster": "Internal Flow",
   "color": "#93B287",
   "gate": null
  },
  {
   "code": "SPI",
   "name": "Spirituality",
   "label": "Spirituality",
   "cluster": "Internal Flow",
   "color": "#A7C49B",
   "gate": null
  },
  {
   "code": "CAR",
   "name": "Career & Achievement",
   "label": "Career &\nAchievement",
   "cluster": "Expansion",
   "color": "#C19A47",
   "gate": null
  },
  {
   "code": "PGR",
   "name": "Personal Growth",
   "label": "Personal\nGrowth",
   "cluster": "Expansion",
   "color": "#CDA95C",
   "gate": null
  },
  {
   "code": "MNP",
   "name": "Meaning & Purpose",
   "label": "Meaning &\nPurpose",
   "cluster": "Expansion",
   "color": "#D9B871",
   "gate": null
  },
  {
   "code": "CEX",
   "name": "Creativity & Expression",
   "label": "Creativity &\nExpression",
   "cluster": "Expansion",
   "color": "#E5C786",
   "gate": null
  }
 ],
 "gates": [
  {
   "header": "G1",
   "domain": "PAR",
   "choice": "1"
  },
  {
   "header": "G2",
   "domain": "SXI",
   "choice": "2"
  }
 ],
 "meta_columns": [
  {
   "header": "Full Name",
   "source": "question",
   "tag": "FULL_NAME"
  },
  {
   "header": "Email",
   "source": "question",
   "tag": "EMAIL"
  },
  {
   "header": "Phone Number",
   "source": "question",
   "tag": "PHONE"
  },
  {
   "header": "StartDate",
   "source": "meta",
   "field": "startDate"
  },
  {
   "header": "EndDate",
   "source": "meta",
   "field": "endDate"
  },
  {
   "header": "Progress",
   "source": "meta",
   "field": "progress"
  },
  {
   "header": "Duration (in seconds)",
   "source": "meta",
   "field": "duration"
  },
  {
   "header": "Finished",
   "source": "meta",
   "field": "finished"
  },
  {
   "header": "DistributionChannel",
   "source": "meta",
   "field": "distributionChannel"
  },
  {
   "header": "Informed Consent",
   "source": "question",
   "tag": "CONSENT"
  }
 ],
 "items": [
  {
   "s": 1,
   "tag": "Q01_FWB_1",
   "code": "FWB_1",
   "domain": "FWB",
   "reverse": true,
   "validity": null
  },
  {
   "s": 2,
   "tag": "Q02_REL_1",
   "code": "REL_1",
   "domain": "REL",
   "reverse": false,
   "validity": null
  },
  {
   "s": 3,
   "tag": "Q03_PWB_1",
   "code": "PWB_1",
   "domain": "PWB",
   "reverse": false,
   "validity": null
  },
  {
   "s": 4,
   "tag": "Q04_CAR_1",
   "code": "CAR_1",
   "domain": "CAR",
   "reverse": true,
   "validity": null
  },
  {
   "s": 5,
   "tag": "Q05_FAM_1",
   "code": "FAM_1",
   "domain": "FAM",
   "reverse": false,
   "validity": null
  },
  {
   "s": 6,
   "tag": "Q06_MWB_1",
   "code": "MWB_1",
   "domain": "MWB",
   "reverse": false,
   "validity": null
  },
  {
   "s": 7,
   "tag": "Q07_LEN_1",
   "code": "LEN_1",
   "domain": "LEN",
   "reverse": true,
   "validity": null
  },
  {
   "s": 8,
   "tag": "Q08_SPI_1",
   "code": "SPI_1",
   "domain": "SPI",
   "reverse": false,
   "validity": null
  },
  {
   "s": 9,
   "tag": "Q09_TMG_1",
   "code": "TMG_1",
   "domain": "TMG",
   "reverse": true,
   "validity": null
  },
  {
   "s": 10,
   "tag": "Q10_CID_1",
   "code": "CID_1",
   "domain": "CID",
   "reverse": false,
   "validity": null
  },
  {
   "s": 11,
   "tag": "Q11_REC_1",
   "code": "REC_1",
   "domain": "REC",
   "reverse": false,
   "validity": null
  },
  {
   "s": 12,
   "tag": "Q12_MNP_1",
   "code": "MNP_1",
   "domain": "MNP",
   "reverse": false,
   "validity": null
  },
  {
   "s": 13,
   "tag": "Q13_SEC_1",
   "code": "SEC_1",
   "domain": "SEC",
   "reverse": false,
   "validity": null
  },
  {
   "s": 14,
   "tag": "Q14_CEX_1",
   "code": "CEX_1",
   "domain": "CEX",
   "reverse": false,
   "validity": null
  },
  {
   "s": 15,
   "tag": "Q15_COM_1",
   "code": "COM_1",
   "domain": "COM",
   "reverse": false,
   "validity": null
  },
  {
   "s": 16,
   "tag": "Q16_PGR_1",
   "code": "PGR_1",
   "domain": "PGR",
   "reverse": false,
   "validity": null
  },
  {
   "s": 17,
   "tag": "Q17_SXI_1",
   "code": "SXI_1",
   "domain": "SXI",
   "reverse": true,
   "validity": null
  },
  {
   "s": 18,
   "tag": "Q18_PAR_1",
   "code": "PAR_1",
   "domain": "PAR",
   "reverse": false,
   "validity": null
  },
  {
   "s": 19,
   "tag": "Q19_MNP_2",
   "code": "MNP_2",
   "domain": "MNP",
   "reverse": true,
   "validity": null
  },
  {
   "s": 20,
   "tag": "Q20_PWB_2",
   "code": "PWB_2",
   "domain": "PWB",
   "reverse": true,
   "validity": null
  },
  {
   "s": 21,
   "tag": "Q21_FAM_2",
   "code": "FAM_2",
   "domain": "FAM",
   "reverse": true,
   "validity": null
  },
  {
   "s": 22,
   "tag": "Q22_TMG_2",
   "code": "TMG_2",
   "domain": "TMG",
   "reverse": false,
   "validity": null
  },
  {
   "s": 23,
   "tag": "Q23_SEC_2",
   "code": "SEC_2",
   "domain": "SEC",
   "reverse": false,
   "validity": null
  },
  {
   "s": 24,
   "tag": "Q24_REL_2",
   "code": "REL_2",
   "domain": "REL",
   "reverse": true,
   "validity": null
  },
  {
   "s": 25,
   "tag": "Q25_V_ATT_1",
   "code": "V_ATT_1",
   "domain": null,
   "reverse": false,
   "validity": "attention"
  },
  {
   "s": 26,
   "tag": "Q26_CID_2",
   "code": "CID_2",
   "domain": "CID",
   "reverse": true,
   "validity": null
  },
  {
   "s": 27,
   "tag": "Q27_CAR_2",
   "code": "CAR_2",
   "domain": "CAR",
   "reverse": false,
   "validity": null
  },
  {
   "s": 28,
   "tag": "Q28_REC_2",
   "code": "REC_2",
   "domain": "REC",
   "reverse": true,
   "validity": null
  },
  {
   "s": 29,
   "tag": "Q29_FWB_2",
   "code": "FWB_2",
   "domain": "FWB",
   "reverse": false,
   "validity": null
  },
  {
   "s": 30,
   "tag": "Q30_SPI_2",
   "code": "SPI_2",
   "domain": "SPI",
   "reverse": true,
   "validity": null
  },
  {
   "s": 31,
   "tag": "Q31_COM_2",
   "code": "COM_2",
   "domain": "COM",
   "reverse": false,
   "validity": null
  },
  {
   "s": 32,
   "tag": "Q32_MWB_2",
   "code": "MWB_2",
   "domain": "MWB",
   "reverse": true,
   "validity": null
  },
  {
   "s": 33,
   "tag": "Q33_PGR_2",
   "code": "PGR_2",
   "domain": "PGR",
   "reverse": true,
   "validity": null
  },
  {
   "s": 34,
   "tag": "Q34_LEN_2",
   "code": "LEN_2",
   "domain": "LEN",
   "reverse": false,
   "validity": null
  },
  {
   "s": 35,
   "tag": "Q35_SXI_2",
   "code": "SXI_2",
   "domain": "SXI",
   "reverse": false,
   "validity": null
  },
  {
   "s": 36,
   "tag": "Q36_PAR_2",
   "code": "PAR_2",
   "domain": "PAR",
   "reverse": false,
   "validity": null
  },
  {
   "s": 37,
   "tag": "Q37_CEX_2",
   "code": "CEX_2",
   "domain": "CEX",
   "reverse": true,
   "validity": null
  },
  {
   "s": 38,
   "tag": "Q38_CAR_3",
   "code": "CAR_3",
   "domain": "CAR",
   "reverse": true,
   "validity": null
  },
  {
   "s": 39,
   "tag": "Q39_LEN_3",
   "code": "LEN_3",
   "domain": "LEN",
   "reverse": true,
   "validity": null
  },
  {
   "s": 40,
   "tag": "Q40_MWB_3",
   "code": "MWB_3",
   "domain": "MWB",
   "reverse": true,
   "validity": null
  },
  {
   "s": 41,
   "tag": "Q41_FWB_3",
   "code": "FWB_3",
   "domain": "FWB",
   "reverse": false,
   "validity": null
  },
  {
   "s": 42,
   "tag": "Q42_SXI_3",
   "code": "SXI_3",
   "domain": "SXI",
   "reverse": false,
   "validity": null
  },
  {
   "s": 43,
   "tag": "Q43_SPI_3",
   "code": "SPI_3",
   "domain": "SPI",
   "reverse": true,
   "validity": null
  },
  {
   "s": 44,
   "tag": "Q44_REL_3",
   "code": "REL_3",
   "domain": "REL",
   "reverse": false,
   "validity": null
  },
  {
   "s": 45,
   "tag": "Q45_PGR_3",
   "code": "PGR_3",
   "domain": "PGR",
   "reverse": false,
   "validity": null
  },
  {
   "s": 46,
   "tag": "Q46_FAM_3",
   "code": "FAM_3",
   "domain": "FAM",
   "reverse": false,
   "validity": null
  },
  {
   "s": 47,
   "tag": "Q47_SEC_3",
   "code": "SEC_3",
   "domain": "SEC",
   "reverse": true,
   "validity": null
  },
  {
   "s": 48,
   "tag": "Q48_COM_3",
   "code": "COM_3",
   "domain": "COM",
   "reverse": true,
   "validity": null
  },
  {
   "s": 49,
   "tag": "Q49_PWB_3",
   "code": "PWB_3",
   "domain": "PWB",
   "reverse": false,
   "validity": null
  },
  {
   "s": 50,
   "tag": "Q50_TMG_3",
   "code": "TMG_3",
   "domain": "TMG",
   "reverse": false,
   "validity": null
  },
  {
   "s": 51,
   "tag": "Q51_REC_3",
   "code": "REC_3",
   "domain": "REC",
   "reverse": true,
   "validity": null
  },
  {
   "s": 52,
   "tag": "Q52_CID_3",
   "code": "CID_3",
   "domain": "CID",
   "reverse": false,
   "validity": null
  },
  {
   "s": 53,
   "tag": "Q53_PAR_3",
   "code": "PAR_3",
   "domain": "PAR",
   "reverse": true,
   "validity": null
  },
  {
   "s": 54,
   "tag": "Q54_V_ATT_2",
   "code": "V_ATT_2",
   "domain": null,
   "reverse": false,
   "validity": "attention"
  },
  {
   "s": 55,
   "tag": "Q55_MNP_3",
   "code": "MNP_3",
   "domain": "MNP",
   "reverse": true,
   "validity": null
  },
  {
   "s": 56,
   "tag": "Q56_CEX_3",
   "code": "CEX_3",
   "domain": "CEX",
   "reverse": false,
   "validity": null
  },
  {
   "s": 57,
   "tag": "Q57_REL_4",
   "code": "REL_4",
   "domain": "REL",
   "reverse": true,
   "validity": null
  },
  {
   "s": 58,
   "tag": "Q58_SEC_4",
   "code": "SEC_4",
   "domain": "SEC",
   "reverse": true,
   "validity": null
  },
  {
   "s": 59,
   "tag": "Q59_FWB_4",
   "code": "FWB_4",
   "domain": "FWB",
   "reverse": true,
   "validity": null
  },
  {
   "s": 60,
   "tag": "Q60_PGR_4",
   "code": "PGR_4",
   "domain": "PGR",
   "reverse": true,
   "validity": null
  },
  {
   "s": 61,
   "tag": "Q61_SPI_4",
   "code": "SPI_4",
   "domain": "SPI",
   "reverse": false,
   "validity": null
  },
  {
   "s": 62,
   "tag": "Q62_CAR_4",
   "code": "CAR_4",
   "domain": "CAR",
   "reverse": false,
   "validity": null
  },
  {
   "s": 63,
   "tag": "Q63_PAR_4",
   "code": "PAR_4",
   "domain": "PAR",
   "reverse": true,
   "validity": null
  },
  {
   "s": 64,
   "tag": "Q64_MWB_4",
   "code": "MWB_4",
   "domain": "MWB",
   "reverse": true,
   "validity": null
  },
  {
   "s": 65,
   "tag": "Q65_CID_4",
   "code": "CID_4",
   "domain": "CID",
   "reverse": true,
   "validity": null
  },
  {
   "s": 66,
   "tag": "Q66_TMG_4",
   "code": "TMG_4",
   "domain": "TMG",
   "reverse": true,
   "validity": null
  },
  {
   "s": 67,
   "tag": "Q67_COM_4",
   "code": "COM_4",
   "domain": "COM",
   "reverse": true,
   "validity": null
  },
  {
   "s": 68,
   "tag": "Q68_FAM_4",
   "code": "FAM_4",
   "domain": "FAM",
   "reverse": false,
   "validity": null
  },
  {
   "s": 69,
   "tag": "Q69_PWB_4",
   "code": "PWB_4",
   "domain": "PWB",
   "reverse": true,
   "validity": null
  },
  {
   "s": 70,
   "tag": "Q70_MNP_4",
   "code": "MNP_4",
   "domain": "MNP",
   "reverse": false,
   "validity": null
  },
  {
   "s": 71,
   "tag": "Q71_SXI_4",
   "code": "SXI_4",
   "domain": "SXI",
   "reverse": true,
   "validity": null
  },
  {
   "s": 72,
   "tag": "Q72_REC_4",
   "code": "REC_4",
   "domain": "REC",
   "reverse": false,
   "validity": null
  },
  {
   "s": 73,
   "tag": "Q73_LEN_4",
   "code": "LEN_4",
   "domain": "LEN",
   "reverse": false,
   "validity": null
  },
  {
   "s": 74,
   "tag": "Q74_V_SD_1",
   "code": "V_SD_1",
   "domain": null,
   "reverse": false,
   "validity": "social_desirability"
  },
  {
   "s": 75,
   "tag": "Q75_CEX_4",
   "code": "CEX_4",
   "domain": "CEX",
   "reverse": true,
   "validity": null
  }
 ]
};
